# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [43]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [44]:
A = np.arange(1, 16).reshape(3,5)

In [46]:
print("Dimension (ndim):", A.ndim)
print("Shape:", A.shape)
print("Size:", A.size)
print("Datatype:", A.dtype)

Dimension (ndim): 2
Shape: (3, 5)
Size: 15
Datatype: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [10]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [36]:
# Elementvis subtraktion
print("Elementvis subtraktion (B - C):")
print(B - C)
print()

# Elementvis multiplikation
print("Elementvis multiplikation (B * C):")
print(B * C)
print()

# Matrismultiplikation
print("Matrismultiplikation (B @ C):")
print(B @ C)

Elementvis subtraktion (B - C):
[[4 4]
 [4 4]]

Elementvis multiplikation (B * C):
[[ 5 12]
 [21 32]]

Matrismultiplikation (B @ C):
[[23 34]
 [31 46]]


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [14]:
D = np.arange(1, 10).reshape(3, 3)
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
# Exponentiera varje element
print("Exponential (np.exp(D)):")
print(np.exp(D))
print()

# Minimivärde i hela matrisen
print("Minimivärde i hela matrisen:", np.min(D))
print()

# Minimivärde i varje rad
print("Minimivärde i varje rad:", np.min(D, axis=1))
print()

# Minimivärde i varje kolumn
print("Minimivärde i varje kolumn:", np.min(D, axis=0))
print()

# Index för minimivärdet i hela matrisen
print("Index för minimum i hela matrisen:", np.argmin(D))
print()

# Index för minimivärdet i varje rad
print("Index för minimum i varje rad:", np.argmin(D, axis=1))
print()

# Summa av alla element
print("Summa av alla element:", np.sum(D))
print()

# Medelvärde för varje kolumn
print("Medelvärde för varje kolumn:", np.mean(D, axis=0))
print()

# Median för varje kolumn
print("Median för varje kolumn:", np.median(D, axis=0))

Exponential (np.exp(D)):
[[ 7.3890561   1.        ]
 [ 2.71828183 20.08553692]]

Minimivärde i hela matrisen: 0

Minimivärde i varje rad: [0 1]

Minimivärde i varje kolumn: [1 0]

Index för minimum i hela matrisen: 1

Index för minimum i varje rad: [1 0]

Summa av alla element: 6

Medelvärde för varje kolumn: [1.5 1.5]

Median för varje kolumn: [1.5 1.5]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [48]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [49]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [50]:
# När man anger färre index än axlar, antar NumPy automatiskt att
# man vill ha alla element längs de återstående axlarna.
# A[1] betyder: hämta rad med index 1, och alla kolumner i den raden.
# Detta är ekvivalent med A[1, :] 
# Alltså returnerar A[1] hela den andra raden: [6, 7, 8, 9, 10]

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [52]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [55]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [28]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
# Koden tar en 1D-array 'a' med 30 element (0-29) och omformar den till 
# en 3D-array 'b' med shape (2, 3, 5).

# Tre axlar betyder:
# - Axel 0: 2 "block" (som 2 staplade matriser)
# - Axel 1: 3 rader i varje block
# - Axel 2: 5 kolumner i varje rad

# -1 i reshape betyder "beräkna denna dimension automatiskt"
# Eftersom vi har 30 element och anger (2, 3, -1), beräknar NumPy: 30/(2*3) = 5

print("Shape för b:", b.shape)
print("Antal dimensioner:", b.ndim)
print("\nFörsta blocket (b[0]):")
print(b[0])
print("\nAndra blocket (b[1]):")
print(b[1])

Shape of b: (2, 3, 5)
Number of dimensions: 3

First block (b[0]):
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Second block (b[1]):
[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [38]:
def add_mult_matrices(matrix1, matrix2, operation):
    """
    Addera eller multiplicera två matriser enligt linjär algebras regler.
    
    Parameters:
    matrix1, matrix2: numpy arrays
    operation: 'add' eller 'multiply'
    
    Returns:
    Resultatet av operationen
    """
    # Validera att inputs är numpy arrays
    if not isinstance(matrix1, np.ndarray):
        raise TypeError("matrix1 måste vara en numpy.ndarray")
    if not isinstance(matrix2, np.ndarray):
        raise TypeError("matrix2 måste vara en numpy.ndarray")
    
    # Validera operation
    if operation not in ['add', 'multiply']:
        raise ValueError("operation måste vara antingen 'add' eller 'multiply'")
    
    if operation == 'add':
        # För addition måste matriserna ha samma shape
        if matrix1.shape != matrix2.shape:
            raise ValueError(f"Matriserna måste ha samma shape för addition. Fick {matrix1.shape} och {matrix2.shape}")
        return matrix1 + matrix2
    
    elif operation == 'multiply':
        # För multiplikation måste kolumner i första matrisen = rader i andra matrisen
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError(f"För multiplikation måste kolumner i första matrisen ({matrix1.shape[1]}) vara lika med rader i andra matrisen ({matrix2.shape[0]})")
        return matrix1 @ matrix2

# Testa funktionen
print("Test 1 - Addition:")
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(add_mult_matrices(A, B, 'add'))

print("\nTest 2 - Multiplikation:")
C = np.array([[1, 2], [3, 4]])
D = np.array([[2, 0], [1, 3]])
print(add_mult_matrices(C, D, 'multiply'))

print("\nTest 3 - Felhantering (olika shapes för addition):")
try:
    E = np.array([[1, 2]])
    F = np.array([[1], [2]])
    add_mult_matrices(E, F, 'add')
except ValueError as e:
    print(f"Fel: {e}")

Test 1 - Addition:
[[ 6  8]
 [10 12]]

Test 2 - Multiplikation:
[[ 4  6]
 [10 12]]

Test 3 - Felhantering (olika shapes för addition):
Fel: Matriserna måste ha samma shape för addition. Fick (1, 2) och (2, 1)


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [41]:
# Hjälpfunktion för vektornorm
def vector_norm(v):
    """Beräkna normen (längden) av en vektor"""
    return np.sqrt(sum([xi**2 for xi in v]))

# Uppgift 10.1.1
x = (4, 3)

print("=== Uppgift 10.1.1 ===")
print("dim x:", len(x))
print("5x:", [5*xi for xi in x])
print("3x:", [3*xi for xi in x])
print("5x + 3x:", [5*xi + 3*xi for xi in x])
print("8x:", [8*xi for xi in x])
print("4x - x:", [4*xi - xi for xi in x])
print("||x||:", vector_norm(x))
print()

# Uppgift 10.1.2
v = (3, 7, 0, 11)

print("=== Uppgift 10.1.2 ===")
print("dim v:", len(v))
print("2v:", [2*vi for vi in v])
print("5v + 2v:", [5*vi + 2*vi for vi in v])
print("4v - 2v:", [4*vi - 2*vi for vi in v])
print("||v||:", vector_norm(v))
print()

# Uppgift 10.1.3
v1 = (4, 3, 1, 5)
v2 = (2, 3, 1, 1)

print("=== Uppgift 10.1.3 ===")
print("||v1||:", vector_norm(v1))

diff = [a - b for a, b in zip(v1, v2)]
print("v1 - v2:", diff)
print("||v1 - v2||:", vector_norm(diff))

=== Uppgift 10.1.1 ===
dim x: 2
5x: [20, 15]
3x: [12, 9]
5x + 3x: [32, 24]
8x: [32, 24]
4x - x: [12, 9]
||x||: 5.0

=== Uppgift 10.1.2 ===
dim v: 4
2v: [6, 14, 0, 22]
5v + 2v: [21, 49, 0, 77]
4v - 2v: [6, 14, 0, 22]
||v||: 13.379088160259652

=== Uppgift 10.1.3 ===
||v1||: 7.14142842854285
v1 - v2: [2, 0, 0, 4]
||v1 - v2||: 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [58]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [60]:
# Kontrollera om v2 är en view eller kopia med 'base'-attributet
print("Är v2 en view? Kontrollera om v2.base är v1:", v2.base is v1)
print()

# Ändra sista elementet i v2
print("Ändrar sista elementet i v2 till 123...")
v2[-1] = 123

print("\nEfter modifiering:")
print("v1:", v1)
print("v2:", v2)
print()

# Svar: Ja, v1 kommer att ändras!
# Varför? Eftersom v2 är en VIEW (inte en kopia) av v1.
# När man slicear med basic indexing (v1[-2:]), skapar NumPy en view
# som delar samma minne som v1. Alla ändringar i v2 påverkar v1.
# Detta är effektivt för stora arrayer, men var försiktig med oavsiktliga ändringar!

print("Förklaring:")
print("v2 är en VIEW av v1, så de delar samma minne.")
print("Ändringar i v2 återspeglas i v1.")

Är v2 en view? Kontrollera om v2.base är v1: True

Ändrar sista elementet i v2 till 123...

Efter modifiering:
v1: [  0   1   2 123]
v2: [  2 123]

Förklaring:
v2 är en VIEW av v1, så de delar samma minne.
Ändringar i v2 återspeglas i v1.
