# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [ ]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [ ]:
A = np.arange(1, 16).reshape(3,5)

In [ ]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

Matris A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Dimension (ndim): 2
Shape: (3, 5)
Size: 15
Datatype: int64



### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

Matris B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matris C:
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]



In [ ]:
print(B - C)
print()
print(B * C)
print()
print(B @ C)

B - C (elementvis subtraktion):
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

B * C (elementvis multiplikation):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

B @ C (matrismultiplikation):
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]



### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [ ]:
D = np.arange(1, 10).reshape(3, 3)
print(D)

Matris D:
[[1 2 3]
 [4 5 6]
 [7 8 9]]



In [ ]:
print(np.exp(D))
print(np.min(D))
print(np.min(D, axis=1))
print(np.min(D, axis=0))
print(np.argmin(D))
print(np.argmin(D, axis=1))
print(np.sum(D))
print(np.mean(D, axis=0))
print(np.median(D, axis=0))

Exponentiera varje element i D:
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minsta värdet i D:
1

Minsta värden per rad:
[1 4 7]

Minsta värden per kolumn:
[1 2 3]

Index för minsta värdet i D (flattened index):
0

Index för minsta värdet per rad:
[0 0 0]

Summan av alla element i D:
45

Medelvärde per kolumn:
[4. 5. 6.]

Median per kolumn:
[4. 5. 6.]



### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [42]:
print(A)

[[1 2]
 [3 4]]


In [43]:
A[1]

array([3, 4])

**Answer:**

In [44]:
# när man skriver A[1] så får man hela raden
# det är samma som A[1, :]

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [45]:
A

array([[1, 2],
       [3, 4]])

In [46]:
for i in A:
    print(i)

[1 2]
[3 4]


In [47]:
for element in A.flat:
    print(element)

1
2
3
4


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [48]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [49]:
# a har 30 element (0-29)
# b omformar det till 3D med shape (2, 3, 5)
# tre axlar betyder 3 dimensioner
# -1 betyder att numpy räknar ut den automatiskt

print(b.shape)

(2, 3, 5)


### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [23]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [51]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [25]:
def add_mult_matrices(matrix1, matrix2, operation):
    if not isinstance(matrix1, np.ndarray):
        print("matrix1 är inte en numpy array")
        return None
    if not isinstance(matrix2, np.ndarray):
        print("matrix2 är inte en numpy array")
        return None
    
    if operation not in ['add', 'multiply']:
        print("operation måste vara add eller multiply")
        return None
    
    if operation == 'add':
        if matrix1.shape != matrix2.shape:
            print("kan inte addera, olika storlek")
            return None
        return matrix1 + matrix2
    
    elif operation == 'multiply':
        if matrix1.shape[1] != matrix2.shape[0]:
            print("kan inte multiplicera, fel storlek")
            return None
        return matrix1 @ matrix2

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(add_mult_matrices(A, B, 'add'))

C = np.array([[1, 2], [3, 4]])
D = np.array([[2, 0], [1, 3]])
print(add_mult_matrices(C, D, 'multiply'))

[[ 6  8]
 [10 12]]
[[ 4  6]
 [10 12]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [ ]:
def vector_norm(v):
    return np.sqrt(sum([xi**2 for xi in v]))

# 10.1.1
x = (4, 3)
print(len(x))
print([5*xi for xi in x])
print([3*xi for xi in x])
print([5*xi + 3*xi for xi in x])
print([8*xi for xi in x])
print([4*xi - xi for xi in x])
print(vector_norm(x))

# 10.1.2
v = (3, 7, 0, 11)
print(len(v))
print([2*vi for vi in v])
print([5*vi + 2*vi for vi in v])
print([4*vi - 2*vi for vi in v])
print(vector_norm(v))

# 10.1.3
v1 = (4, 3, 1, 5)
v2 = (2, 3, 1, 1)
print(vector_norm(v1))
diff = [a - b for a, b in zip(v1, v2)]
print(diff)
print(vector_norm(diff))

dim: 2
5x: [20, 15]
3x: [12, 9]
5x + 3x: [32, 24]
8x: [32, 24]
4x - x: [12, 9]
längd: 5.0
dim: 4
2v: [6, 14, 0, 22]
5v + 2v: [21, 49, 0, 77]
4v - 2v: [6, 14, 0, 22]
längd: 13.379088160259652
längd v1: 7.14142842854285
v1 - v2: [2, 0, 0, 4]
längd av diff: 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeskögskolan" by using Python. 

In [ ]:
# uppgift 10.2.4

### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [26]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [27]:
# kolla med base
print(v2.base is v1)

v2[-1] = 123

print(v1)
print(v2)

# ja v1 ändras också
# v2 är en view så de delar minne

True
[  0   1   2 123]
[  2 123]
